### ISSUE TITLE
ADDA version

### ISSUE THREAD

**Issue by inzhevatkin** [adda-team/adda-gui#14]
You can display the result of "adda -V" somewhere, i.e. what version of ADDA GUI is using. You can run this when you start the GUI in order to at the same time check that ADDA is present, where it should be, and the version is not less than it should be. (if the ADDA version is less or higher than expected, you can issue a warning). Although it may leave an opportunity for different binaries to be used in each project.
You can display the version when the Help->About button is clicked (under the line with the GUI version).

**Comment by myurkin** [comment]
For now, it is sufficient to have one set of binaries for all projects (i.e. they are specified in global settings rather than in project-specific ones).

**Comment by dsmunev** [comment]
done [https://github.com/adda-team/adda-gui/releases/tag/v0.4.1](url)
