### ISSUE TITLE
adda-gui.exe launch problem

### ISSUE THREAD

**Issue by inzhevatkin** [adda-team/adda-gui#2]
From time to time adda-gui.exe fails to run. I only see the inscription "Please wait ...". I could not establish at what events it occurs (possibly by accident, but not sure). In the latest version (v0.2.1beta, v0.2.3beta), I have not encountered such a problem yet.

**Comment by myurkin** [comment]
Konstantin, can you please try to reproduce this bug in release 0.3. If it does not appear any more, please close the issue.

**Comment by inzhevatkin** [comment]
The bug is not reproduced in the release 0.3.
