### ISSUE TITLE
Incorrect settings.xml

### ISSUE THREAD

**Issue by inzhevatkin** [adda-team/adda-gui#32]
The problem that appears if there is an incorrect settings.xml (including with a different path on the disk) - you need to solve it somehow broader than deleting this file. Even if the user downloads the GUI without this file, he can run it in one folder and then copy everything to another location. That is, the GUI itself must either repair or delete this file (probably, here it is enough to write the logic for updating the path).

**Comment by myurkin** [comment]
This is probably fixed in the latest release. Dmitry, is that true?

**Comment by dsmunev** [comment]
fixed [https://github.com/adda-team/adda-gui/releases/tag/v0.4.1](url)
