### ISSUE TITLE
Russian text

### ISSUE THREAD

**Issue by inzhevatkin** [adda-team/adda-gui#33]
When I click on the result graph (mueller) with the right mouse button, a menu with Russian text appears on the screen. I think a translation into English needs to be done.

**Comment by myurkin** [comment]
Yest, the Russian language is probably inherited from the system default (by some clever container). But until we make the whole GUI multi-lingual, all text should be English irrespective of the system settings.

**Comment by dsmunev** [comment]
fixed [https://github.com/adda-team/adda-gui/releases/tag/v0.4.1](url)
