### ISSUE TITLE
Workflow for creating packages

### ISSUE THREAD

**Issue by myurkin** [adda-team/adda-gui#37]
Currently we have open source and final ready-to-use packages for three systems. But we lack an instruction how the latter are produced from the former. This instruction should include the description of external resources (like portable Java runtimes for various systems) and where they should be placed. After that some script should be prepared that produces all the packages.

**Comment by myurkin** [comment]
Related to that are simplifications for Linux packages. It should be possible to set the proper execution flags during the packaging. Then users won't have to do it on their side.

**Comment by dsmunev** [comment]
done [https://github.com/adda-team/adda-gui/releases/tag/v0.4.1](url)
