### ISSUE TITLE
Signing the GUI app for MacOS

### ISSUE THREAD

**Issue by myurkin** [adda-team/adda-gui#39]
It is worth studying the existing rules for becoming official Apple developer to be able to sign apps. How much does it cost? Is there any special conditions for free (GPL) software.

It will improve the user experience on MacOS.

**Comment by alkichigin** [comment]
To sign an app, one needs to have an active Developer account, which costs 99$ per year. There is a manual for XCode https://developer.apple.com/support/code-signing/, but maybe other developer platforms also can be adapted.
However, if one wants the desired application to be added in the App store, GPL license is incompatible with the App store rules.

**Comment by myurkin** [comment]
Well, then we better proceed with Homebrew (#40) - so that anyone can compile it from scratch.
