### ISSUE TITLE
Improvement of linux package

### ISSUE THREAD

**Issue by myurkin** [adda-team/adda-gui#41]
I have tested the Linux package and it works perfectly. Here are a few ideas for further improvements:
* In the following `sudo` is not needed
  ```
  sudo chmod +x ./adda-gui.sh
  sudo chmod +x ./jbr/bin/java
  ```
  However, as mentioned in https://github.com/adda-team/adda-gui/issues/37#issuecomment-895190369, these lines need to be avoided altogether by proper packaging.

* when instructing the user to compile ADDA himself, several lines can be combined into
  ```
  sudo apt_get install gcc gfortran make libfftw3-dev
  ```

**Comment by dsmunev** [comment]
done [https://github.com/adda-team/adda-gui/releases/tag/v0.4.1](url)
