### ISSUE TITLE
Bug: Propagation direction dropdown

### ISSUE THREAD

**Issue by userx14** [adda-team/adda-gui#47]
Hi,
when selection propagation directions from the dropdown menu in the Basic tab, the resulting option is selected inconsistently, depending which option was selected before:
When first `Along z-axis` and then `Along x-axis` is selected, the propagation is set to `[0; 0; 1]`.
When first `Along y-axis` and then `Along x-axis` is selected, the propagation is set to `[0; 1; 0]`.
If I read the manual correctely, the option should be `[1; 0; 0]` for x-propagation.
I'm using Version 0.9.5 on Windows 10.

<img width="703" alt="Capture" src="https://github.com/adda-team/adda-gui/assets/12860358/51b8c92b-d445-4209-be3a-0a41422501bd">

**Comment by myurkin** [comment]
I have confirmed the issue. Seems that the previous value of `-prop` is used in the command line. The same problem is when `Along y-axis` is selected.

**Comment by dsmunev** [comment]
fyi @userx14 @myurkin 
fixed  [Version 0.9.6 3D](https://github.com/adda-team/adda-gui/releases/tag/v0.9.6)
@userx14 Thanks!
