### ISSUE TITLE
Problem with displaying program elements

### ISSUE THREAD

**Issue by inzhevatkin** [adda-team/adda-gui#5]
From time to time, when minimizing and then maximizing the GUI window, the display of elements (buttons, text) does not work. I see a blank white screen. If you move the mouse over the window, the elements begin to appear. In the latest version (v0.2.1beta, v0.2.3beta), I have not encountered such a problem yet.

**Comment by myurkin** [comment]
Konstantin, can you please try to reproduce this bug in release 0.3. If it does not appear any more, please close the issue.

**Comment by inzhevatkin** [comment]
The bug is not reproduced in the release 0.3.
