### ISSUE TITLE
Default button

### ISSUE THREAD

**Issue by inzhevatkin** [adda-team/adda-gui#8]
It is worth adding the Default button. When working with the adda-gui, it is sometimes convenient to return it to its original state. Closing the program does not return it to its original state, which is both positive and negative.

**Comment by myurkin** [comment]
Such button should probably be called "Clear" or "Clear All"

**Comment by myurkin** [comment]
This seems to be fixed, but, Dmitry, please write here the specific commit, when it was done (and close it).

**Comment by dsmunev** [comment]
done [https://github.com/adda-team/adda-gui/releases/tag/v0.4.1](url)
