### ISSUE TITLE
New project

### ISSUE THREAD

**Issue by inzhevatkin** [adda-team/adda-gui#9]
I create a project (File-> New-> Project). Then it is possible to choose a different path where the new project will be located. The program creates a new project, but I cannot start it with the Run button. The program did not recognize that the created folder is a project. If you close the program and then open it, then the new folder is not displayed on the left in the project tree.

**Comment by myurkin** [comment]
Related to this, currently GUI starts with `My Documents` when one wishes to change the path for storing a new project

**Comment by myurkin** [comment]
In the release 0.3 (under Windows) the projects are stored in `.../My Documents/AddaGui` but the selection for the folder for a new project (when a selection window opens) starts one level above at `.../My Documents` (that is incorrect).

**Comment by dsmunev** [comment]
fixed [Version 0.9.6 3D](https://github.com/adda-team/adda-gui/releases/tag/v0.9.6)
